// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxrjmjayqbzlserskgjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cmptamF5cWJ6bHNlcnNrZ2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3ODU2MDAsImV4cCI6MjA0OTM2MTYwMH0.DJ5sLzCv4Ep4uxiZCL0gaUWyTVRomKqJ7slbRmbGeKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);